...
AndreyWild/hotel pull request #1
Opened 2021-08-25 17:19 UTC by AndreyWild

2021-08-26 05:52 UTC, SenlaCoursesAdmin reviewed
что за название ветки?

2021-08-26 06:53 UTC, SenlaCoursesAdmin requested changes
create/diagram FIN.mwb  что за файл?

2021-08-26 06:53 UTC, SenlaCoursesAdmin commented on dao/src/main/resources/hibernate.cfg.xml
> +<?xml version='1.0' encoding='utf-8'?>
в чем отличие dao/src/main/java/hibernate.cfg.xml

2021-08-26 06:53 UTC, SenlaCoursesAdmin commented on model/pom.xml
> +<!--        </dependency>-->
почисти помник если не надо удаляй комменты

2021-08-26 19:40 UTC, AndreyWild commented on dao/src/main/resources/hibernate.cfg.xml
> +<?xml version='1.0' encoding='utf-8'?>
Это были эталон и Франкенштейн =)

2021-08-26 19:43 UTC, AndreyWild commented on model/pom.xml
> +<!--        </dependency>-->
поправил

2021-08-27 10:40 UTC, SenlaCoursesAdmin requested changes

2021-08-27 10:40 UTC, SenlaCoursesAdmin commented on dao/pom.xml
> +<!--    </build>-->
кому? зачем?

2021-08-27 10:40 UTC, SenlaCoursesAdmin commented on dao/pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.hibernate/hibernate-entitymanager -->
кому? зачем?

2021-08-27 10:40 UTC, SenlaCoursesAdmin commented on dao/pom.xml
> +
кому? зачем?

2021-08-27 10:40 UTC, SenlaCoursesAdmin commented on dao/src/main/java/Hotel.java
> +
кому? зачем?

2021-08-27 10:40 UTC, SenlaCoursesAdmin commented on dao/src/main/java/com/senla/util/HibernateAnnotationsUtil.java
> +                    .addPackage("com/senla/model/entityes")
entities

2021-08-27 10:40 UTC, SenlaCoursesAdmin commented on dao/src/main/java/com/senla/util/HibernateAnnotationsUtil.java
> +            throw new ExceptionInInitializerError(ex);
а зачем это делатЬ?

2021-08-27 10:40 UTC, SenlaCoursesAdmin commented on dao/src/main/resources/hibernate.cfg.xml
> +<?xml version='1.0' encoding='utf-8'?>
а кому эти комментарии?

2021-08-27 11:02 UTC, AndreyWild commented on dao/pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.hibernate/hibernate-entitymanager -->
Что именно, комментарий или hibernate-core?

2021-08-27 11:03 UTC, AndreyWild commented on dao/src/main/java/Hotel.java
> +
Это проверочный класс. Уберу

2021-08-27 11:05 UTC, AndreyWild commented on dao/src/main/java/com/senla/util/HibernateAnnotationsUtil.java
> +                    .addPackage("com/senla/model/entityes")
I'm sorry for my english. My bad =)

2021-08-27 11:06 UTC, AndreyWild commented on dao/src/main/java/com/senla/util/HibernateAnnotationsUtil.java
> +            throw new ExceptionInInitializerError(ex);
Зачем сообщение в логе или  зачем исключение?

2021-08-29 18:31 UTC, merged