add task14
AndreyWild/hotel pull request #2
Opened 2021-08-29 20:26 UTC by AndreyWild

2021-08-30 07:45 UTC, SenlaCoursesAdmin requested changes

2021-08-30 07:45 UTC, SenlaCoursesAdmin commented on service/src/main/java/com/senla/service/impl/GuestService.java
> +    @Transactional
не проще ли над классом поставить? одну чем над каждым?

2021-08-30 07:45 UTC, SenlaCoursesAdmin commented on controller/src/main/java/com/senla/controller/util/MyConfig.java
> +            dataSource.setPassword("root");
а разве это не прописано в пропертях?

2021-08-30 07:45 UTC, SenlaCoursesAdmin commented on api/src/main/java/com/senla/api/service/IMaintenanceService.java
> +    void setMaintenanceDao(IMaintenanceDao maintenanceDao);
вот это тоже явно лишнее

2021-08-30 08:40 UTC, AndreyWild commented on api/src/main/java/com/senla/api/service/IMaintenanceService.java
> +    void setMaintenanceDao(IMaintenanceDao maintenanceDao);
Это было создано чтобы сеттер появился в бине, я хардкодил =)

2021-08-30 08:41 UTC, AndreyWild commented on controller/src/main/java/com/senla/controller/util/MyConfig.java
> +            dataSource.setPassword("root");
когда берет из проперти оч долго думает, я пока оставил явное указание.

2021-08-30 08:42 UTC, AndreyWild commented on service/src/main/java/com/senla/service/impl/GuestService.java
> +    @Transactional
Проще, но я не знал сработает ли, поэтому указывал явно.

2021-08-30 10:58 UTC, SenlaCoursesAdmin commented on controller/src/main/java/com/senla/controller/util/MyConfig.java
> +            dataSource.setPassword("root");
выбери что-то

2021-08-30 10:58 UTC, SenlaCoursesAdmin commented on api/src/main/java/com/senla/api/service/IMaintenanceService.java
> +    void setMaintenanceDao(IMaintenanceDao maintenanceDao);
удаляем

2021-08-30 11:34 UTC, SenlaCoursesAdmin requested changes

2021-08-30 11:34 UTC, SenlaCoursesAdmin commented on controller/src/main/java/com/senla/controller/Hotel.java
> +public class Hotel {
@Component

2021-08-30 11:34 UTC, SenlaCoursesAdmin commented on controller/src/main/java/com/senla/controller/util/MyConfig.java
> +        ComboPooledDataSource dataSource = new ComboPooledDataSource(); // подключение к БД
почему не DataSource

2021-08-30 11:34 UTC, SenlaCoursesAdmin commented on controller/src/main/resources/application.properties
> +spring.database.driver=com.mysql.cj.jdbc.Driver
а почему ресурсы к бд находятся в пакете контроллеров?

2021-08-30 13:40 UTC, SenlaCoursesAdmin requested changes

2021-08-30 13:40 UTC, SenlaCoursesAdmin commented on controller/src/main/java/com/senla/controller/Hotel.java
> +                new AnnotationConfigApplicationContext(MyConfig.class);
ApplicationContext context = new AnnotationConfigApplicationContext(MyConfig.class);

2021-08-30 13:40 UTC, SenlaCoursesAdmin commented on controller/src/main/java/com/senla/controller/util/MyConfig.java
> +@ComponentScan(basePackages = {"com.senla.api",
@ComponentScan(basePackages = "com.senla")

2021-09-03 04:42 UTC, SenlaCoursesAdmin requested changes

2021-09-03 04:42 UTC, SenlaCoursesAdmin commented on controller/src/main/java/com/senla/controller/configuration/ControllerConfig.java
> +@ComponentScan("com.senla") // откуда брать компоненты
скан можно поставить и над стартовым классом . ради этого класс держать не разумно

2021-09-03 04:42 UTC, SenlaCoursesAdmin commented on dao/src/main/java/com/senla/configuration/DaoJpaConfig.java
> +//@ComponentScan(basePackages = {"com.senla.api", "com.senla.model.entities", "com.senla.service.impl", "com.senla.dao.impl"})
повторения?

2021-09-03 04:42 UTC, SenlaCoursesAdmin commented on dao/src/main/java/com/senla/configuration/DaoJpaConfig.java
> +        return transactionManager;
зачем 2 конфигурации удали чтото одно оставь

2021-09-03 04:42 UTC, SenlaCoursesAdmin commented on dao/src/main/java/com/senla/util/EntityManagerUtil.java
>  public class EntityManagerUtil {
удали

2021-09-03 04:42 UTC, SenlaCoursesAdmin commented on dao/src/main/java/com/senla/util/HibernateAnnotationsUtil.java
> +//@Log4j
аналогично

2021-09-03 04:42 UTC, SenlaCoursesAdmin commented on log4j.xml
> +            <appender-ref ref="CONSOLE_INFO" level="info"/>
что это за файл?

2021-09-05 08:28 UTC, AndreyWild commented on log4j.xml
> +            <appender-ref ref="CONSOLE_INFO" level="info"/>
настрйоки логера

2021-09-06 05:03 UTC, SenlaCoursesAdmin requested changes
удали все комментарии

2021-09-12 15:03 UTC, merged